bsideproject/palette-api-server

.gitignore
server/logs/api.log
src/main/java/com/palette/BaseEntity.java
src/main/java/com/palette/user/UserController.java
src/main/java/com/palette/user/service/UserService.java

- refresh token 을 검증 후 access token을 갱신하는 api 추가했습니다.
- #22 에 있었던 jpa id generation strategy를 auto에서 identity로 변경했습니다.
- gitignore 파일에 log 디렉토리를 추가했습니다.

[#25, #26, #28] 토큰 갱신 기능 추가

---

build.gradle
src/main/java/com/palette/diary/fetcher/dto/CreateDiaryInput.java
src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
src/main/java/com/palette/diary/repository/DiaryRepository.java
src/main/java/com/palette/user/UserController.java
src/main/java/com/palette/user/domain/User.java
src/main/java/com/palette/user/fetcher/UserFetcher.java
src/main/java/com/palette/user/fetcher/dto/LoginRequest.java
src/main/java/com/palette/user/fetcher/dto/TokenResponse.java
src/main/java/com/palette/user/service/UserService.java
src/main/resources/schema/color.graphqls
src/main/resources/schema/common.graphql
src/main/resources/schema/diary.graphqls
src/main/resources/schema/user.graphql

내 정보를 가지고 오는 myProfile query
- common.graphql에 공통 type인 Query와 Mutation 분리
- User.diaries를 @DgsData로 연결
- DiaryRepository에 user의 daries를 가지고 올수 있는 findUserDiaries 메소드 추가

Feat: myProfile query

---

src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/fetcher/dto/CreateDiaryOutput.java
src/main/java/com/palette/diary/fetcher/dto/InviteDiaryInput.java
src/main/java/com/palette/diary/fetcher/dto/InviteDiaryOutput.java
src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
src/main/java/com/palette/diary/repository/DiaryRepository.java
src/main/resources/schema/diary.graphqls

아직 개발되지 않아 정적 데이터 넣은 부분
- 토큰 파싱 후 산출된 유저정보로 유저 엔티티 조회
- 예외처리

Feat: 초대코드를 통한 일기그룹 유저 초대 (#31)

---

src/main/java/com/palette/user/domain/User.java

userEntity의 agreeWithTerms가 @Builder.Default 되어 있지 않아 userService.createAccessToken에서 에러 발생

fix: userEntity agreeWithTerms builder default 설정

---

src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
src/main/java/com/palette/diary/repository/HistoryRepository.java
src/main/java/com/palette/exception/common/GlobalErrorType.java
src/main/java/com/palette/exception/graphql/ColorNotFoundException.java
src/main/java/com/palette/exception/graphql/DiaryExistUserException.java
src/main/java/com/palette/exception/graphql/DiaryNotFoundException.java
src/main/java/com/palette/exception/graphql/DiaryOutedUserException.java
src/main/java/com/palette/exception/graphql/DiaryOverUserException.java
src/main/java/com/palette/exception/graphql/InviteCodeNotFoundException.java
src/main/java/com/palette/exception/graphql/ProgressedHistoryException.java
src/main/java/com/palette/exception/graphql/UserNotFoundException.java

- 일기 생성 API
- 일기 초대 API
- 히스토리 생성 API
- 일기 리스트 조회  API

Feat: 일기관련 API 예외처리

---

src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
src/main/java/com/palette/user/UserController.java
src/main/java/com/palette/user/service/UserService.java

refresh token과 access token에 userId 추가

fix: userId added in tokens

---

src/main/java/com/palette/BaseEntity.java
src/main/java/com/palette/aop/LoginUserAspect.java
src/main/java/com/palette/common/P6spyConfig.java
src/main/java/com/palette/common/P6spyPrettySqlFormatter.java
src/main/java/com/palette/diary/domain/History.java
src/main/java/com/palette/diary/domain/Page.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/fetcher/dto/CreateHistoryInput.java
src/main/java/com/palette/diary/repository/PageRepository.java
src/main/java/com/palette/exception/RestExceptionHandler.java
src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
src/main/java/com/palette/resolver/LoginUser.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/schema/entity.graphql

- 엔티티 LocalDateTime -> OffsetDateTime 변경
- graphql LocalTime -> DateTime 변경
- 토큰에서 userId 추출
- 일기 리스트 조회  API
- 해당 일기 최근 페이지 조회 API
graphql의 하위 엔티티를 조회하기 위한 쿼리가 많이 나가는 점 리펙토링 필요

Feat: 일기 리스트 및 최근 페이지 조회 (#41), Chore: p6spy 추가 (#72)

---

src/main/java/com/palette/common/BaseRepository.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java

원격에 fix 브랜치가 있어서 fix/diary로 생성못했네요.. 😂

Fix: 일기 최근 글 조회시 3개 제한 및 생성일자 내림차순

---

src/main/java/com/palette/diary/fetcher/DiaryFetcher.java

API가 지금 안되서 바로 머지할께요~ 같은 로직이라 중복제거했습니다~

Fix: Page.author 중복 제거

---

src/main/java/com/palette/color/domain/Color.java
src/main/java/com/palette/diary/domain/Image.java
src/main/java/com/palette/diary/domain/Page.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/fetcher/dto/CreateDiaryInput.java

- page - image 엔티티 1:N 관계 설정
- createPage 로직 수정
- diaryGroup isAdmin 기본값 true
- color 엔티티 불필요한 값 제거
dev 디비에 적용 했고 createPage 테스트 시 정상 삽입 확인 되었습니다.

Fix: page-image 1:N 관계 설정 및 기타 수정

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

로그파일 dockervolumd 매핑 실패로 인한 로그설정을 xml로 수정

Chore: 로그백 xml 설정으로 변경

---

build.gradle
src/main/java/com/palette/common/S3Properties.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/exception/GraphqlExceptionHandler.java
src/main/java/com/palette/exception/RestExceptionHandler.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

- 파라미터 스토어 등록(업로드 도메인 정보, 센트리 dns)
※ ncp 서버에 센트리 구축하면 dns 주소만 수정하면 되서 코드는 미리 확인 부탁드립니다 :)

Feat: 센트리 설정

---

src/main/java/com/palette/common/PageInput.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/repository/PageRepository.java
src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
src/main/resources/schema/diary.graphqls

- PageInput 필드 추가
- getLocalContext 사용(diaries, histories)
- 기타 쿼리 수정

Fix: 일기 수정

---

src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/repository/PageRepository.java
src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java

Refactor: 히스토리 홈 조회 N+1 해결

---

src/main/java/com/palette/alarmhistory/service/AlarmHistoryService.java
src/main/java/com/palette/infra/fcm/PushNotificationService.java

Fix: 알림 데이터에 alarmHistoryId 추가

---

src/main/java/com/palette/alarmhistory/fetcher/dto/ReadAlarmHistoriesInput.java

Fix: 알림 읽음처리 mutation 요청값 배열로 변경

---

src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/service/DiaryService.java
src/main/java/com/palette/infra/fcm/PushNotificationService.java
src/main/java/com/palette/infra/scheduler/job/HistoryRemindOne.java
src/main/java/com/palette/infra/scheduler/job/HistoryRemindTwo.java

1차알림은 12 * 선택일수
ex) 3일일기 -> 36시간 남았을 때 알림
2차알림은 24시간 남았을 때

Fix: 남은기간 알림 job 등록

---

src/main/java/com/palette/exception/RestExceptionHandler.java
src/main/java/com/palette/exception/common/GlobalErrorType.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

- https://www.notion.so/bside/80339c76f15445aebbc5cdf861383e9c
예외 코드, 문구 참고

Fix: Multipart 업로드 예외처리 추가 (#142)

---

src/main/java/com/palette/infra/fcm/PushNotificationService.java

현재 : 000님과000님과교환일기가 시작됐어요.30일 후
변경 : 000님과 000님의 교환일기가 시작됐어요. 30일 후
(띄어쓰기, 과→의)

Fix: 일기 시작 알림 문구 수정

---

src/main/java/com/palette/diary/dataloader/PastHistoriesDataLoader.java
src/main/java/com/palette/diary/dataloader/dto/PastHistoriesDto.java
src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
src/main/java/com/palette/diary/fetcher/dto/PastHistory.java
src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
src/main/resources/schema/entity.graphql

Fix: 일기 홈 조회 API response 수정

---

src/main/java/com/palette/alarmhistory/repository/AlarmHistoryQueryRepository.java

Fix: 알림 히스토리 조회 orderby 조건 추가
